name: Team111 项目单元测试CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install GCC compile environment
        run: sudo apt-get update && sudo apt-get install gcc -y
      - name: Compile unit test code
        run: cd test && gcc all_test.c -o test
      - name: Run all unit test cases
        run: cd test && ./test
